[package]
name = "villain"
version = "0.1.0"
edition = "2024"
description = "A tiling-first Wayland compositor and window manager for the Knave Desktop Environment"
license = "MIT"

[workspace]
members = []
resolver = "3"

[dependencies]
libc = "0.2"
toml = "0.9"
smithay = { version = "0.7.0", default-features = false, features = [
    "backend_winit",
    "backend_drm",
    "backend_gbm",
    "backend_udev",
    "backend_libinput",
    "backend_session_libseat",
    "desktop",
    "wayland_frontend",
    "xwayland",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
xcursor = "0.3.11"
knave-desktop-api = { git = "ssh://git@github.com/knave-de/knave.git", rev = "1eb63fe" }
knave-config = { git = "ssh://git@github.com/knave-de/knave.git", rev = "1eb63fe" }
serde_json = "1"
base64 = "0.22"
png = "0.18"

[dev-dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
